-- MySQL Script generated by MySQL Workbench
-- Wed Sep 28 14:40:29 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema colheita_fresca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema colheita_fresca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `colheita_fresca` DEFAULT CHARACTER SET utf8 ;
USE `colheita_fresca` ;

-- -----------------------------------------------------
-- Table `colheita_fresca`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colheita_fresca`.`tb_categoria` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colheita_fresca`.`tb_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colheita_fresca`.`tb_user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `cpf` BIGINT NULL,
  `cnpj` BIGINT NULL,
  `end` VARCHAR(255) NOT NULL,
  `tipo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colheita_fresca`.`tb_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colheita_fresca`.`tb_produtos` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `valor` DECIMAL(4,2) NOT NULL,
  `kg` VARCHAR(255) NOT NULL,
  `estoque` INT NOT NULL,
  `imagem` VARCHAR(255) NOT NULL,
  `tb_categoria_id` BIGINT NULL,
  `tb_user_id` BIGINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_produtos_tb_categoria_idx` (`tb_categoria_id` ASC) VISIBLE,
  INDEX `fk_tb_produtos_tb_user1_idx` (`tb_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_produtos_tb_categoria`
    FOREIGN KEY (`tb_categoria_id`)
    REFERENCES `colheita_fresca`.`tb_categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_produtos_tb_user1`
    FOREIGN KEY (`tb_user_id`)
    REFERENCES `colheita_fresca`.`tb_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
